version: "3"

services:
  sway:
    image: ghcr.io/pod-arcade/desktop:main
    environment:
      - MQTT_HOST=ws://localhost:8080/mqtt
      - DESKTOP_ID=dolphin-aio
      # - DESKTOP_PSK=""
    user: root
    privileged: true
    volumes:
      - shared_pulse:/tmp/pulse
      - shared_sway:/tmp/sway
      - shared_x11:/tmp/.X11-unix
      - shared_dri:/dev/dri
      - /dev/dri:/host/dev/dri
      
  yuzu:
    image: ghcr.io/pod-arcade/example-yuzu:main
    restart: on-failure
    links:
      - sway
    depends_on:
      - sway
    environment:
      - WAYLAND_DISPLAY=wayland-1
      - DISPLAY=:0
      - XDG_RUNTIME_DIR=/tmp/sway
      - PULSE_SERVER=unix:/tmp/pulse
    volumes:
      - shared_pulse:/tmp/pulse
      - shared_sway:/tmp/sway
      - shared_x11:/tmp/.X11-unix
      - shared_dri:/dev/dri
volumes:
  shared_pulse:
  shared_sway:
  shared_x11:
  shared_dri:
