version: "3"

services:
  server:
    image: ghcr.io/pod-arcade/server:main
    restart: on-failure
    ports:
      - "8080:8080" # HTTP Web Port (likely won't work without a TLS LB in front)
      # - "1883:1883" # not really needed
      - "8443:8443" # needed for Web TLS
    privileged: true
    environment:
      AUTH_REQUIRED: 'false'
      TLS_PORT: '8443'
      SERVE_TLS: 'true'
      # AUTH_REQUIRED: 'true'
      # CLIENT_PSK: client_psk_goes_here
      # DESKTOP_PSK: desktop_psk_goes_here
      ICE_SERVERS: '[{"urls":["stun:stun.l.google.com:19302"]}]'