version: "3"

services:
  dolphin:
    image: ghcr.io/pod-arcade/example-dolphin-aio:main
    restart: on-failure
    privileged: true
    environment:
      - MQTT_HOST=ws://localhost:8080/mqtt
      - DESKTOP_ID=dolphin-aio
      # - DESKTOP_PSK=""